In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('./tableau_project.csv')
data.head()

,Unnamed: 0,journey_id,vehicle_type_id,start_type,start_at,start_lat,start_lon,end_at,end_lat,end_lon,...,price_distance,price_duration,distance,duration,source,rider_waiting_time,driver_waiting_time,price_supplements,discount,rating
0,0,93e6d216088af74c32183283d4bb2953,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-12-16 11:08:59,19.431363,-99.195362,2017-12-16 11:37:32,19.406438,-99.175260,...,"5,204",0,"7,943","1,058",Android,590,48,662,0,9.0
1,1,444b084ec64244919afadfba879876a3,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-12-16 11:06:16,19.431567,-99.195368,2017-12-16 11:07:21,NaN,NaN,...,0,0,0,0,iPhone,NaN,NaN,0,0,9.0
2,2,dbcc57f4e7606a71c74c6e4666a977a4,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-24 22:58:37,19.422052,-99.174499,2017-11-24 23:27:05,19.438666,-99.180821,...,"3,552",0,"3,054",689,Android,923,4,0,0,10.0
3,3,1ffe9a24033847148c683574985df56c,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-12-16 09:17:08,19.433119,-99.154844,2017-12-16 09:17:30,19.290148,-99.144407,...,0,0,0,0,iPhone,NaN,NaN,0,0,9.0
4,4,fb1ef7d070724482a33be41f27737ea5,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-24 18:11:00,19.440996,-99.183581,2017-11-24 18:31:31,19.422815,-99.174865,...,"2,974",12,"2,859",887,iPhone,329,36,0,0,8.0

In [3]:
columns=list(data.columns)
tp=data['start_type'].value_counts()

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3864 entries, 0 to 3863
Data columns (total 22 columns):
Unnamed: 0             3864 non-null int64
journey_id             3864 non-null object
vehicle_type_id        3864 non-null object
start_type             3864 non-null object
start_at               3864 non-null object
start_lat              3864 non-null float64
start_lon              3864 non-null float64
end_at                 3864 non-null object
end_lat                3807 non-null float64
end_lon                3807 non-null float64
end_state              3864 non-null object
price                  3844 non-null object
price_distance         2812 non-null object
price_duration         2812 non-null object
distance               3844 non-null object
duration               3844 non-null object
source                 3864 non-null object
rider_waiting_time     2733 non-null object
driver_waiting_time    2685 non-null object
price_supplements      3864 non-null object
discount               3844 non-null object
rating                 3864 non-null float64
dtypes: float64(5), int64(1), object(16)
memory usage: 664.2+ KB

In [5]:
data1=data[['price','start_lat','start_lon','end_lat','end_lon','end_state','distance','duration','rating','rider_waiting_time','vehicle_type_id']]

In [6]:
data1.dropna()

,price,start_lat,start_lon,end_lat,end_lon,end_state,distance,duration,rating,rider_waiting_time,vehicle_type_id
0,"5,866",19.431363,-99.195362,19.406438,-99.175260,drop off,"7,943","1,058",9.0,590,077866c3fd1a75f51ca7f8eae166ae32
2,"4,000",19.422052,-99.174499,19.438666,-99.180821,drop off,"3,054",689,10.0,923,077866c3fd1a75f51ca7f8eae166ae32
4,"4,000",19.440996,-99.183581,19.422815,-99.174865,drop off,"2,859",887,8.0,329,077866c3fd1a75f51ca7f8eae166ae32
5,"4,000",19.421856,-99.174361,19.440311,-99.184146,drop off,"3,176","1,028",8.0,73,077866c3fd1a75f51ca7f8eae166ae32
7,"6,449",19.419962,-99.171955,19.441434,-99.183503,drop off,"3,008","1,505",10.0,770,077866c3fd1a75f51ca7f8eae166ae32
9,"8,063",19.438666,-99.180821,19.423103,-99.174878,drop off,"3,034",958,10.0,"1,655",077866c3fd1a75f51ca7f8eae166ae32
11,"6,924",19.421541,-99.174171,19.442719,-99.201140,drop off,"5,083","1,253",10.0,729,077866c3fd1a75f51ca7f8eae166ae32
12,"4,000",19.422815,-99.174865,19.406438,-99.175260,drop off,"2,766",841,9.0,633,077866c3fd1a75f51ca7f8eae166ae32
15,"9,404",19.441434,-99.183503,19.439331,-99.202260,drop off,"8,254","3,566",10.0,589,077866c3fd1a75f51ca7f8eae166ae32
17,"5,299",19.406353,-99.175294,19.432267,-99.154651,drop off,"5,600","1,073",8.0,477,077866c3fd1a75f51ca7f8eae166ae32
18,"4,000",19.422815,-99.174865,19.406438,-99.175260,drop off,"3,187",930,9.0,576,077866c3fd1a75f51ca7f8eae166ae32
21,"4,000",19.440754,-99.183578,19.422815,-99.174865,drop off,"3,073","1,259",8.0,873,077866c3fd1a75f51ca7f8eae166ae32
22,"4,000",19.441409,-99.184146,19.427445,-99.170818,drop off,"2,923","1,485",10.0,205,077866c3fd1a75f51ca7f8eae166ae32
23,"4,000",19.421830,-99.174441,19.440311,-99.184146,drop off,"2,516",783,8.0,856,077866c3fd1a75f51ca7f8eae166ae32
24,"6,582",19.438666,-99.180821,19.406134,-99.176266,drop off,"4,849","1,682",10.0,"1,011",077866c3fd1a75f51ca7f8eae166ae32
26,"4,000",19.441256,-99.183574,19.422815,-99.174865,drop off,"2,714",838,6.0,163,077866c3fd1a75f51ca7f8eae166ae32
27,"5,438",19.419962,-99.171955,19.441434,-99.183503,drop off,"3,895","2,270",10.0,648,077866c3fd1a75f51ca7f8eae166ae32
30,"5,610",19.441406,-99.184136,19.419962,-99.171955,drop off,"6,751","3,660",10.0,925,077866c3fd1a75f51ca7f8eae166ae32
31,"10,534",19.406120,-99.176239,19.438666,-99.180821,drop off,"5,686","1,037",10.0,"2,844",077866c3fd1a75f51ca7f8eae166ae32
32,"4,000",19.422954,-99.174981,19.423091,-99.170269,drop off,701,746,6.0,"1,171",21620ea5749f2e0679a8c72c7fbafb9e
33,"5,738",19.438253,-99.181061,19.432267,-99.154651,drop off,"3,927","1,538",8.0,256,077866c3fd1a75f51ca7f8eae166ae32
34,"4,000",19.427800,-99.170115,19.432267,-99.154651,drop off,"1,754",851,9.0,328,077866c3fd1a75f51ca7f8eae166ae32
35,"4,000",19.421960,-99.174559,19.438666,-99.180821,drop off,"3,275",935,10.0,909,21620ea5749f2e0679a8c72c7fbafb9e
36,"4,908",19.441411,-99.184123,19.419962,-99.171955,drop off,"3,793","2,177",10.0,365,21620ea5749f2e0679a8c72c7fbafb9e
38,"19,028",19.406954,-99.175520,19.421496,-99.077809,drop off,"14,696","4,070",9.0,"1,276",077866c3fd1a75f51ca7f8eae166ae32
40,"29,421",19.377219,-99.254503,19.421496,-99.077809,drop off,"21,346","6,070",9.0,"2,239",21620ea5749f2e0679a8c72c7fbafb9e
41,"4,000",19.422770,-99.174517,19.420010,-99.166312,drop off,"1,315",294,8.0,984,21620ea5749f2e0679a8c72c7fbafb9e
42,"4,000",19.422916,-99.175002,19.423091,-99.170269,drop off,"1,360",419,6.0,"1,436",21620ea5749f2e0679a8c72c7fbafb9e
43,"4,000",19.441253,-99.183557,19.422815,-99.174865,drop off,"2,763","2,066",6.0,503,21620ea5749f2e0679a8c72c7fbafb9e
45,"4,000",19.441140,-99.183570,19.422815,-99.174865,drop off,"3,260","1,545",8.0,257,21620ea5749f2e0679a8c72c7fbafb9e
...,...,...,...,...,...,...,...,...,...,...,...
3823,"5,204",19.376909,-99.254901,19.379486,-99.253980,drop off,"1,574","1,393",9.0,427,21620ea5749f2e0679a8c72c7fbafb9e
3824,"4,000",19.379486,-99.253980,19.376909,-99.254901,drop off,"1,899",582,9.0,551,21620ea5749f2e0679a8c72c7fbafb9e
3825,"4,211",19.423187,-99.175033,19.441411,-99.183701,drop off,"4,177","1,198",7.0,280,21620ea5749f2e0679a8c72c7fbafb9e
3826,"4,000",19.421780,-99.174397,19.441356,-99.183848,drop off,"2,604","1,066",7.0,250,21620ea5749f2e0679a8c72c7fbafb9e
3827,"4,000",19.441036,-99.183582,19.423091,-99.170269,drop off,"2,163","1,319",8.0,177,21620ea5749f2e0679a8c72c7fbafb9e
3828,"14,075",19.423058,-99.170411,19.498778,-99.231474,drop off,"12,878","1,183",7.0,702,21620ea5749f2e0679a8c72c7fbafb9e
3829,"4,000",19.420656,-99.169980,19.413779,-99.164922,drop off,"1,061",250,8.0,795,21620ea5749f2e0679a8c72c7fbafb9e
3830,"17,874",19.422761,-99.175110,19.356000,-99.275269,drop off,"19,298","2,386",9.0,519,21620ea5749f2e0679a8c72c7fbafb9e
3831,"15,258",19.498778,-99.231474,19.423058,-99.170411,drop off,"13,632","1,270",8.0,381,21620ea5749f2e0679a8c72c7fbafb9e
3833,"5,586",19.423157,-99.170397,19.441380,-99.183926,drop off,"3,769","1,115",8.0,302,21620ea5749f2e0679a8c72c7fbafb9e
3835,"4,000",19.441380,-99.183926,19.423103,-99.174878,drop off,"3,769","1,265",9.0,263,21620ea5749f2e0679a8c72c7fbafb9e
3839,"17,800",19.423159,-99.174806,19.356000,-99.275269,drop off,"15,001","2,020",9.0,498,21620ea5749f2e0679a8c72c7fbafb9e
3840,"17,503",19.498972,-99.231669,19.423091,-99.170269,drop off,"14,854","2,456",8.0,524,21620ea5749f2e0679a8c72c7fbafb9e
3841,"29,387",19.379486,-99.253980,19.402877,-99.098333,drop off,"29,868","4,626",9.0,676,21620ea5749f2e0679a8c72c7fbafb9e
3842,"10,852",19.419770,-99.165930,19.379486,-99.253980,drop off,"14,602","1,654",9.0,142,21620ea5749f2e0679a8c72c7fbafb9e
3844,"4,000",19.423091,-99.170269,19.432232,-99.147815,drop off,"2,593","1,487",9.0,326,21620ea5749f2e0679a8c72c7fbafb9e
3847,"18,610",19.356000,-99.275269,19.441503,-99.183563,drop off,"17,033","2,145",9.0,503,21620ea5749f2e0679a8c72c7fbafb9e
3848,"4,000",19.379486,-99.253980,19.376909,-99.254901,drop off,"1,809","1,023",9.0,456,21620ea5749f2e0679a8c72c7fbafb9e
3849,"4,421",19.423091,-99.170269,19.441380,-99.183926,drop off,"3,025","1,041",9.0,132,21620ea5749f2e0679a8c72c7fbafb9e
3850,"4,000",19.376909,-99.254901,19.379486,-99.253980,drop off,"1,583",662,9.0,243,21620ea5749f2e0679a8c72c7fbafb9e
3851,"4,281",19.379486,-99.253980,19.376909,-99.254901,drop off,"1,622","1,167",9.0,311,21620ea5749f2e0679a8c72c7fbafb9e
3852,"7,544",19.441380,-99.183926,19.423091,-99.170269,drop off,"4,260","1,556",9.0,285,21620ea5749f2e0679a8c72c7fbafb9e
3853,"17,681",19.356000,-99.275269,19.422749,-99.174937,drop off,"15,204","2,171",9.0,69,21620ea5749f2e0679a8c72c7fbafb9e
3854,"4,512",19.423044,-99.174936,19.441503,-99.183563,drop off,"3,541","1,049",9.0,473,21620ea5749f2e0679a8c72c7fbafb9e
3856,"11,052",19.425045,-99.170860,19.355050,-99.162281,drop off,"14,041","1,448",6.0,394,21620ea5749f2e0679a8c72c7fbafb9e
3857,"29,892",19.425047,-99.170855,19.260422,-99.100854,drop off,"40,514","5,439",7.0,499,21620ea5749f2e0679a8c72c7fbafb9e
3858,"11,031",19.425045,-99.170860,19.355143,-99.162525,drop off,"14,056","1,691",6.0,495,21620ea5749f2e0679a8c72c7fbafb9e
3859,"4,134",19.435400,-99.148699,19.425045,-99.170860,drop off,"3,204",857,6.0,650,21620ea5749f2e0679a8c72c7fbafb9e
3860,"5,752",19.425045,-99.170860,19.432602,-99.133205,drop off,"4,417","1,137",6.0,330,21620ea5749f2e0679a8c72c7fbafb9e
3862,"4,000",19.425390,-99.207499,19.432602,-99.133205,rider cancel,5,252,6.0,423,21620ea5749f2e0679a8c72c7fbafb9e

In [7]:
data1.head()

,price,start_lat,start_lon,end_lat,end_lon,end_state,distance,duration,rating,rider_waiting_time,vehicle_type_id
0,"5,866",19.431363,-99.195362,19.406438,-99.175260,drop off,"7,943","1,058",9.0,590,077866c3fd1a75f51ca7f8eae166ae32
1,0,19.431567,-99.195368,NaN,NaN,rider cancel,0,0,9.0,NaN,077866c3fd1a75f51ca7f8eae166ae32
2,"4,000",19.422052,-99.174499,19.438666,-99.180821,drop off,"3,054",689,10.0,923,077866c3fd1a75f51ca7f8eae166ae32
3,0,19.433119,-99.154844,19.290148,-99.144407,rider cancel,0,0,9.0,NaN,077866c3fd1a75f51ca7f8eae166ae32
4,"4,000",19.440996,-99.183581,19.422815,-99.174865,drop off,"2,859",887,8.0,329,077866c3fd1a75f51ca7f8eae166ae32

In [8]:
data1['rating'].value_counts()

9.0     1390
8.0      930
10.0     616
6.0      572
7.0      355
4.0        1
Name: rating, dtype: int64

In [9]:
data1 = data1.drop(data1[data1['rating']==4].index)

In [10]:
data1['rating'].value_counts()

9.0     1390
8.0      930
10.0     616
6.0      572
7.0      355
Name: rating, dtype: int64

In [11]:
data1.to_csv('./taxis.csv', sep='\t')